name: Gobichat
version: '${project.version}'
main: com.github.kumo0621.gobichat.Gobichat
api-version: 1.16
commands:
  gobi:
    permission: gobi
  random:
    permission: random
  allrandom:
    permission: allrandom
permissions:
  gobi:
    default: op
  random:
    default: op
  allrandom:
    default: op